services:
  postgres:
    image: "postgres:15"
    container_name: rlarndg_db
    environment:
      POSTGRES_USER: rustlang-es
      POSTGRES_PASSWORD: rustlang-es
      POSTGRES_DB: rlarndg

  rlarndg:
    container_name: rustlanges/rlarndg:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LITCRYPT_ENCRYPT_KEY: ${LITCRYPT_ENCRYPT_KEY}
        STRIPE_SECRET: ${STRIPE_SECRET}
        DATABASE_URL: "postgres://rustlang-es:rustlang-es@postgres/rlarndg"
    depends_on:
      - postgres
    ports:
      - "10020:80"
