
services:
    postgres:
        image: "postgres:15"
        container_name: rlarndg_db
        environment:
            POSTGRES_USER: rustlang-es
            POSTGRES_PASSWORD: rustlang-es
            POSTGRES_DB: rlarndg
        networks:
            - rlarndg_network

    rlarndg:
        container_name: rlarndg
        build:
            context: .
            dockerfile: Dockerfile
            args:
                STRIPE_SECRET: ${STRIPE_SECRET}
                DATABASE_URL: "postgres://rustlang-es:rustlang-es@rlarndg_network/rlarndg"
        depends_on:
            - postgres
        ports:
            - "10020:80"
        networks:
            - rlarndg_network

networks:
    rlarndg_network:
