
CREATE TABLE keys (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) NOT NULL,
	token VARCHAR(100) NOT NULL,
	paid NUMERIC(5, 2) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
